### ISSUE TITLE
feat(mafia): Fiddled players can see who is speaking, but not the contents of the message

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#1649]
Acceptance Criteria:
- Instead of blocking the text of other players entirely for players with the Fiddled effect, Fiddled players will see messages without useful content
- Chat messages are formatted eg. "Golbolco says something, but you cannot hear them!"

**Comment by drewsworthh** [comment]
just made a pull request for this feature fiddler-change

**Comment by Golbolco** [comment]
> just made a pull request for this feature fiddler-change

Tested it and it appears to have the opposite effect
![image](https://github.com/user-attachments/assets/2812b740-91aa-441e-82f8-f781abc94d4c)
If you are fiddled you are the only one whose speech is visible; everyone else's speech is obscured

**Comment by drewsworthh** [comment]
When you remove the "message = originalMessage;" under the if(message.fiddled) statement it works as intended with a small bug of it looking like graveyard text. If someone knows how to fix that it'll be perfect otherwise i'll try to fix it soon. I'm pretty sure it's under the message.modified that makes it look like graveyard text.

**Comment by Golbolco** [comment]
It's not that bad if it looks like GY text and can't be fixed. But if you want, feel free to create a new css theme for the fiddled text.
